# Generated by Django 4.1.1 on 2022-09-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_id_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(null=True, upload_to='C:\\Pycharm_Projects\\portfolio\\static/img/projects/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.TextField(null=True),
        ),
    ]
