# Generated by Django 4.1.1 on 2022-09-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='text',
            field=models.TextField(max_length=800, null=True),
        ),
    ]
